# Generated by Django 6.0.3 on 2026-03-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='craft',
            name='type',
        ),
        migrations.AddField(
            model_name='craft',
            name='craft_type',
            field=models.CharField(choices=[('wood', 'Резьба по дереву'), ('metal', 'Кузнечное дело'), ('felt', 'Шырдак')], default='wood', max_length=50),
        ),
        migrations.AlterField(
            model_name='craft',
            name='latitude',
            field=models.FloatField(default=42.8746),
        ),
        migrations.AlterField(
            model_name='craft',
            name='longitude',
            field=models.FloatField(default=74.5698),
        ),
        migrations.AlterField(
            model_name='craft',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='craft',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region'),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='backend.craft')),
            ],
        ),
    ]
