# Generated by Django 6.0.3 on 2026-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='craft_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='craft',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
