# Generated by Django 6.0.3 on 2026-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_craft_craft_category_craft_experience_craft_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='craft_type',
            field=models.CharField(choices=[('wood', 'Резьба по дереву'), ('metal', 'Кузнечное дело'), ('felt', 'Шырдак'), ('textile', 'Ткачество'), ('jewelry', 'Ювелирное дело'), ('ceramics', 'Керамика'), ('embroidery', 'Вышивка'), ('leather', 'Кожевенное ремесло')], default='wood', max_length=50),
        ),
    ]
